// brief-lib.mjs — build deterministic briefs from KDD work artifacts.
// Pure functions plus one process call (spec-graph filter --format json).
// No npm dependencies: the frontmatter subset we need is parsed by hand.
import { execFileSync } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';

/** Split a spec file into its YAML frontmatter text and Markdown body. */
export function parseFrontmatter(text) {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(text);
  return m ? { fm: m[1], body: m[2] } : { fm: '', body: text };
}

/** A scalar `key: value` at the top level of the frontmatter, unquoted. */
export function scalarField(fm, key) {
  const m = new RegExp(`^${key}:[ \\t]*(.*?)[ \\t]*$`, 'm').exec(fm);
  if (!m) return null;
  return m[1].replace(/^["']|["']$/g, '') || null;
}

/** A top-level list of scalars, either inline `key: [a, b]` or block `key:\n  - a`. */
export function listField(fm, key) {
  const inline = new RegExp(`^${key}:[ \\t]*\\[([^\\]]*)\\][ \\t]*$`, 'm').exec(fm);
  if (inline) return inline[1].split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
  const block = new RegExp(`^${key}:[ \\t]*\\r?\\n((?:[ \\t]+-[^\\n]*\\r?\\n?)+)`, 'm').exec(fm);
  if (!block) return [];
  return block[1].split(/\r?\n/).map((l) => l.replace(/^[ \t]+-[ \t]*/, '').trim().replace(/^["']|["']$/g, '')).filter(Boolean);
}

/** The `id:` of every entry under `sources:` (a block list of mappings). */
export function sourceIds(fm) {
  const block = /^sources:[ \t]*\r?\n((?:[ \t]+[^\n]*\r?\n?)+)/m.exec(fm);
  if (!block) return [];
  const lines = block[1].split(/\r?\n/);
  const items = [];
  for (const line of lines) {
    if (/^[ \t]+-[ \t]/.test(line)) items.push([line]);
    else if (items.length) items[items.length - 1].push(line);
  }
  const ids = [];
  for (const item of items) {
    for (const line of item) {
      const m = /^[ \t]*(?:-[ \t]+)?id:[ \t]*(\S+)/.exec(line);
      if (m) { ids.push(m[1]); break; }
    }
  }
  return ids;
}

/** `ID@version` → {id, version}; a bare ID has version null. */
export function splitPin(ref) {
  const at = ref.indexOf('@');
  return at === -1 ? { id: ref, version: null } : { id: ref.slice(0, at), version: ref.slice(at + 1) };
}

/** All specs of a directory as spec-graph nodes (id, layer, version, file, body, files, …). */
export function loadNodes(cliPath, specsDir) {
  const out = execFileSync('node', [cliPath, '--specs', specsDir, 'filter', '--format', 'json'], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  return JSON.parse(out);
}

export function findNode(nodes, id) {
  return nodes.find((n) => n.id === id) || null;
}

/** Text under `## <heading>` (exact, case-sensitive) up to the next `## `. */
export function sectionOf(body, heading) {
  const lines = body.split(/\r?\n/);
  const start = lines.findIndex((l) => l.trim() === `## ${heading}`);
  if (start === -1) return '';
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) if (/^## /.test(lines[i])) { end = i; break; }
  return lines.slice(start + 1, end).join('\n').trim();
}

/** One activated/equipped spec: header with pin check, then the full body. */
export function renderSpecBlock(node, pin) {
  const head = `### ${node.id} @${pin ?? node.version} (${node.layer}, file version ${node.version}) — ${node.file}`;
  const drift = pin && pin !== node.version
    ? `\n**PIN DRIFT:** pinned ${pin}, file is ${node.version} — read the current text, report the drift to the controller.\n`
    : '';
  return `${head}\n${drift}\n${(node.body || '').trim()}\n`;
}

/** One fragment: its body plus the raw files it lists (report.md, tests…). */
export function renderFragBlock(node) {
  let out = `### ${node.id} (${node.source_type || 'fragment'}, captured ${node.captured_at || 'n/a'}) — ${node.file}\n\n${(node.body || '').trim()}\n`;
  const dir = dirname(node.file);
  for (const f of node.files || []) {
    const p = join(dir, f);
    if (existsSync(p)) out += `\n#### ${f}\n\n${readFileSync(p, 'utf8').trim()}\n`;
    else out += `\n#### ${f}\n\n_(missing on disk)_\n`;
  }
  return out;
}

function missing(id, what) { return `### ${id}\n\n_(${what} not found in the graph — report this to the controller)_\n`; }

/** The task brief. `taskText` is the raw task file (frontmatter included). */
export function buildTaskBrief({ nodes, taskNode, planNode, taskText }) {
  const { fm } = parseFrontmatter(taskText);
  const activates = listField(fm, 'activates').map(splitPin);
  const equips = listField(fm, 'equips').map(splitPin);
  const frags = sourceIds(fm).filter((id) => /^FRAG-/.test(id));
  const parts = [];
  parts.push(`# Task brief — ${taskNode.id}\n`);
  parts.push(`Generated by task-brief from \`${taskNode.file}\` (plan ${planNode ? planNode.id : 'unknown'}). Read this first — it is your requirements, with the exact values to use verbatim. Sections 2–4 are the knowledge that binds this task: their rules are requirements, not optional context.\n`);
  parts.push(`## 1. Task\n\n${taskText.trim()}\n`);
  parts.push(`## 2. Architecture Impact (${planNode ? planNode.id : 'no plan'})\n\n${planNode ? (sectionOf(planNode.body || '', 'Architecture Impact') || '_(the plan has no Architecture Impact section)_') : '_(parent plan not found)_'}\n`);
  parts.push(`## 3. Activated knowledge\n\n${activates.length ? activates.map(({ id, version }) => { const n = findNode(nodes, id); return n ? renderSpecBlock(n, version) : missing(id, 'activated spec'); }).join('\n') : '_(this task activates no knowledge — activates: [])_\n'}`);
  if (equips.length) parts.push(`## 3b. Equipped capabilities\n\n${equips.map(({ id, version }) => { const n = findNode(nodes, id); return n ? renderSpecBlock(n, version) : missing(id, 'equipped artifact'); }).join('\n')}`);
  parts.push(`## 4. Evidence (fragments cited in sources)\n\n${frags.length ? frags.map((id) => { const n = findNode(nodes, id); return n ? renderFragBlock(n) : missing(id, 'fragment'); }).join('\n') : '_(no fragments cited)_\n'}`);
  return parts.join('\n');
}

/** The review brief: what the WRK-SPEC demands, what the plan constrains, what knowledge binds. */
export function buildReviewBrief({ nodes, specNode, specText, planNode }) {
  const { fm, body } = parseFrontmatter(specText);
  const activates = listField(fm, 'activates').map(splitPin);
  const equips = listField(fm, 'equips').map(splitPin);
  const frags = sourceIds(fm).filter((id) => /^FRAG-/.test(id));
  const parts = [];
  parts.push(`# Review brief — ${specNode.id}\n`);
  parts.push(`Generated by review-brief from \`${specNode.file}\`${planNode ? ` and \`${planNode.file}\`` : ''}. The WRK-SPEC is the authority, the plan is its argument, the activated specs are its constraints — verify the diff against all three.\n`);
  parts.push(`## 1. Acceptance criteria (${specNode.id})\n\n${sectionOf(body, 'Acceptance Criteria') || '_(none stated)_'}\n`);
  parts.push(`## 2. Constraints (${specNode.id})\n\n${sectionOf(body, 'Constraints') || '_(none stated)_'}\n`);
  parts.push(`## 3. Architecture Impact (${planNode ? planNode.id : 'no plan'})\n\n${planNode ? (sectionOf(planNode.body || '', 'Architecture Impact') || '_(the plan has no Architecture Impact section)_') : '_(no WRK-PLAN for this spec)_'}\n`);
  parts.push(`## 4. Activated knowledge\n\n${activates.length ? activates.map(({ id, version }) => { const n = findNode(nodes, id); return n ? renderSpecBlock(n, version) : missing(id, 'activated spec'); }).join('\n') : '_(this work activates no knowledge — activates: [])_\n'}`);
  if (equips.length) parts.push(`## 4b. Equipped capabilities\n\n${equips.map(({ id, version }) => { const n = findNode(nodes, id); return n ? renderSpecBlock(n, version) : missing(id, 'equipped artifact'); }).join('\n')}`);
  parts.push(`## 5. Evidence (fragments cited in sources)\n\n${frags.length ? frags.map((id) => { const n = findNode(nodes, id); return n ? renderFragBlock(n) : missing(id, 'fragment'); }).join('\n') : '_(no fragments cited)_\n'}`);
  return parts.join('\n');
}
